pluginManagement {
	repositories {
		resolutionStrategy {
			eachPlugin {
				if (requested.id.id == 'bio.terra.test-runner-plugin') {
					useModule("bio.terra:terra-test-runner:${requested.version}")
				}
			}
		}
		mavenCentral()
		maven {
			// todo: plugins-snapshot not provisioned yet in GAR
			url 'https://broadinstitute.jfrog.io/artifactory/plugins-snapshot'
		}
		gradlePluginPortal()
	}
}

rootProject.name = 'drshub'
include 'service', 'integration', 'client-resttemplate'
