deploy_env: ${DEPLOY_ENV:dev} # since there's a default, define this once

drshub:
  bondUrl: https://broad-bond-${deploy_env}.appspot.com
  samUrl: https://sam.dsde-${deploy_env}.broadinstitute.org
  externalcredsUrl: https://externalcreds.dsde-${deploy_env}.broadinstitute.org

  compactIdHosts:
    # it is important for case-insensitive matching that the keys here are all lower case
    "dg.4503": gen3.biodatacatalyst.nhlbi.nih.gov
    "dg.712c": staging.gen3.biodatacatalyst.nhlbi.nih.gov
    "dg.anv0": staging.theanvil.io
    "dg.4dfc": nci-crdc-staging.datacommons.io
    "dg.f82a1a": gen3staging.kidsfirstdrc.org
    "dg.test0": ctds-test-env.planx-pla.net

  drsProviders:
    anvil:
      name: NHGRI Analysis Visualization and Informatics Lab-space (The AnVIL)
      hostRegex: '.*\.theanvil\.io'
      metadataAuth: false
      bondProvider: anvil
      accessMethodConfigs:
        - type: gs
          auth: fence_token
          fetchAccessUrl: false
    bioDataCatalyst:
      name: BioData Catalyst (BDC)
      hostRegex: '.*\.biodatacatalyst\.nhlbi\.nih\.gov|wb-mock-drs-dev\.storage\.googleapis\.com'
      metadataAuth: false
      bondProvider: fence
      accessMethodConfigs:
        - type: gs
          auth: fence_token
          fetchAccessUrl: false
    crdc:
      name: NCI Cancer Research / Proteomics Data Commons (CRDC / PDC)
      hostRegex: '.*\.datacommons\.io'
      metadataAuth: false
      bondProvider: dcf_fence
      accessMethodConfigs:
        - type: gs
          auth: fence_token
          fetchAccessUrl: false
        - type: s3
          auth: fence_token
          fetchAccessUrl: true
    kidsFirst:
      name: Gabriella Miller Kids First DRC
      hostRegex: '.*\.kidsfirstdrc\.org'
      metadataAuth: false
      bondProvider: kids_first
      accessMethodConfigs:
        - type: s3
          auth: fence_token
          fetchAccessUrl: true
    passport:
      name: Passport Test Provider
      hostRegex: 'ctds-test-env\.planx-pla\.net'
      metadataAuth: false
      bondProvider: dcf_fence
      accessMethodConfigs:
        - type: gs
          auth: passport
          fetchAccessUrl: true
          fallbackAuth: fence_token
        - type: s3
          auth: passport
          fetchAccessUrl: true
          fallbackAuth: fence_token
      mTlsConfig:
        keyPath: rendered/ras-mtls-client.key
        certPath: rendered/ras-mtls-client.crt

    terraDataRepo:
      name: Terra Data Repo (TDR)
      hostRegex: '.*data.*[-.](?:broadinstitute\.org|terra\.bio)'
      metadataAuth: true
      useAliasesForLocalizationPath: true
      accessMethodConfigs:
        - type: gs
          auth: current_request
          fetchAccessUrl: false
        - type: https
          auth: current_request
          fetchAccessUrl: true # Used for Azure

logging:
  level.bio.terra.externalcreds: ${DRSHUB_LOG_LEVEL:debug}
  pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application:
    name: drshub
    version: ${drshub.version.gitHash:unknown}

  config.import: classpath:rendered/version.properties

  jackson.serialization.indent_output: true

  main.banner-mode: off

  profiles.include:
    - ${DEPLOY_ENV:dev}

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false

terra.common:
  tracing:
    stackdriverExportEnabled: ${CLOUD_TRACE_ENABLED:false}
    samplingRate: ${SAMPLING_PROBABILITY:0}

---
spring.config.activate.on-profile: prod
drshub:
  compactIdHosts:
    "dg.4503": gen3.biodatacatalyst.nhlbi.nih.gov
    "dg.712c": staging.gen3.biodatacatalyst.nhlbi.nih.gov
    "dg.anv0": gen3.theanvil.io
    "dg.4dfc": nci-crdc.datacommons.io
    "dg.f82a1a": data.kidsfirstdrc.org
