deploy_env: ${DEPLOY_ENV:dev} # since there's a default, define this once

drshub:
  bondUrl: https://broad-bond-${deploy_env}.appspot.com
  samUrl: https://sam.dsde-${deploy_env}.broadinstitute.org
  externalcredsUrl: https://externalcreds.dsde-${deploy_env}.broadinstitute.org

  drsProviders:
    anvil:
      name: NHGRI Analysis Visualization and Informatics Lab-space (The AnVIL)
      hostRegex: '.*\.theanvil\.io'
      metadataAuth: false
      bondProvider: anvil
      accessMethodConfigs:
        - type: gs
          auth: fence_token
          fetchAccessUrl: false
    bioDataCatalyst:
      name: BioData Catalyst (BDC)
      hostRegex: '.*\.biodatacatalyst\.nhlbi\.nih\.gov|wb-mock-drs-dev\.storage\.googleapis\.com'
      metadataAuth: false
      bondProvider: fence
      accessMethodConfigs:
        - type: gs
          auth: fence_token
          fetchAccessUrl: true
    crdc:
      name: NCI Cancer Research / Proteomics Data Commons (CRDC / PDC)
      hostRegex: '.*\.datacommons\.io'
      metadataAuth: false
      bondProvider: dcf_fence
      accessMethodConfigs:
        - type: gs
          auth: fence_token
          fetchAccessUrl: true
        - type: s3
          auth: fence_token
          fetchAccessUrl: true
    kidsFirst:
      name: Gabriella Miller Kids First DRC
      hostRegex: '.*\.kidsfirstdrc\.org'
      metadataAuth: false
      bondProvider: kids_first
      accessMethodConfigs:
        - type: s3
          auth: fence_token
          fetchAccessUrl: true
    terraDataRepo:
      name: Terra Data Repo (TDR)
      hostRegex: '.*data.*[-.](?:broadinstitute\.org|terra\.bio)'
      metadataAuth: true
      useAliasesForLocalizationPath: true
      accessMethodConfigs:
        - type: gs
          auth: current_request
          fetchAccessUrl: true
        - type: https
          auth: current_request
          fetchAccessUrl: true # Used for Azure
  pencilsDownSeconds: 58
  asyncThreads: ${TOMCAT_MAX_THREADS:200}

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080
  tomcat:
    # Tomcat defaults: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.server.server.tomcat.accept-count
    threads:
      max: ${TOMCAT_MAX_THREADS:200}
      min-spare: ${TOMCAT_MIN_SPARE_THREADS:10}
    accept-count: ${TOMCAT_ACCEPT_COUNT:100}

spring:
  application:
    name: drshub
    version: ${drshub.version.gitHash:unknown}

  config.import: classpath:rendered/version.properties

  jackson.serialization.indent_output: true

  main.banner-mode: off

  profiles.include:
    - ${DEPLOY_ENV:dev}

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false

terra.common:
  tracing:
    stackdriverExportEnabled: ${CLOUD_TRACE_ENABLED:false}
    samplingRate: ${SAMPLING_PROBABILITY:0}

---
# not-prod
# we want this test passport provider in all non-prod envs
# TDR is the only host that has specific values for each lower env
spring.config.activate.on-profile: '!prod'
drshub:
  drsProviders:
    passport:
      name: Passport Test Provider
      hostRegex: 'ctds-test-env\.planx-pla\.net'
      metadataAuth: false
      bondProvider: dcf_fence
      accessMethodConfigs:
        - type: gs
          auth: passport
          fetchAccessUrl: true
          fallbackAuth: fence_token
        - type: s3
          auth: passport
          fetchAccessUrl: true
          fallbackAuth: fence_token
      mTlsConfig:
        keyPath: rendered/ras-mtls-client.key
        certPath: rendered/ras-mtls-client.crt
  signedUrlDuration: 1h
  compactIdHosts:
    "dg.712c": staging.gen3.biodatacatalyst.nhlbi.nih.gov # biodatacatalyst staging
    "dg.anv0": staging.theanvil.io # this is the old anvil CIB, the new one (drs.anv0) is set explicitly for each env
    "dg.4dfc": nci-crdc-staging.datacommons.io # cancer research data commons
    "dg.f82a1a": gen3staging.kidsfirstdrc.org # kidsfirst
    "dg.test0": ctds-test-env.planx-pla.net # passport test
---
# prod
spring.config.activate.on-profile: prod
drshub:
  compactIdHosts:
    "dg.4503": gen3.biodatacatalyst.nhlbi.nih.gov # biodatacatalyst
    "dg.anv0": gen3.theanvil.io # old anvil
    "drs.anv0": data.terra.bio # new anvil (hosted on TDR)
    "dg.4dfc": nci-crdc.datacommons.io # cancer research data commons
    "dg.f82a1a": data.kidsfirstdrc.org # kidsfirst
---
# dev
spring.config.activate.on-profile: dev
drshub:
  compactIdHosts:
    "drs.anv0": jade.datarepo-dev.broadinstitute.org
---
# staging
spring.config.activate.on-profile: staging
drshub:
  compactIdHosts:
    "drs.anv0": data.staging.envs-terra.bio
---
# alpha
spring.config.activate.on-profile: alpha
drshub:
  compactIdHosts:
    "drs.anv0": data.alpha.envs-terra.bio
