plugins {
	id 'idea'
	id 'jacoco'
	id 'java'

	id 'org.springframework.boot'

	id 'com.diffplug.spotless'
	id 'com.github.ben-manes.versions' version '0.53.0'
	id 'com.google.cloud.tools.jib'
	id 'com.gorylenko.gradle-git-properties' version '2.5.3'
	id 'io.freefair.lombok'
	id 'org.hidetake.swagger.generator'
  	id 'com.srcclr.gradle' version '3.1.12'
	id 'org.sonarqube'
	id 'io.sentry.jvm.gradle' version '5.12.2'
}

repositories {
	mavenCentral()
	maven { url 'https://us-central1-maven.pkg.dev/dsp-artifact-registry/libs-snapshot/' }
	maven { url 'https://us-central1-maven.pkg.dev/dsp-artifact-registry/libs-release/' }
}


description = 'DRS Hub'

apply from: 'publishing.gradle'
apply from: 'spring.gradle'
apply from: 'generators.gradle'
apply from: 'tooling.gradle'
apply from: 'analysis.gradle'

dependencies {
	annotationProcessor 'org.immutables:value:2.11.6'

	implementation('bio.terra:terra-common-lib:1.1.39-SNAPSHOT') {
		// remove transitive database deps, drshub has no db
		exclude group: 'org.liquibase', module: 'liquibase-core'
		exclude group: 'bio.terra', module: 'stairway-gcp'
		exclude group: 'bio.terra', module: 'stairway'
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-data-jdbc'
		exclude group: 'com.google.oauth-client', module: 'google-oauth-client'
		exclude group: 'org.postgresql', module: 'postgresql'
	}
	implementation 'org.broadinstitute.dsde.workbench:sam-client_2.13:v0.0.332'
	implementation 'bio.terra:externalcreds-client-resttemplate:1.83.0-SNAPSHOT'
	implementation 'org.codehaus.janino:janino:3.1.12' // Provides if/else xml parsing for logback config

	// google
	implementation platform('com.google.cloud:libraries-bom:26.71.0')
	implementation 'com.google.oauth-client:google-oauth-client'
	implementation 'com.google.cloud:google-cloud-storage'
	implementation 'com.google.cloud:spring-cloud-gcp-starter-logging:4.9.0'

	// For Micrometer metrics gathering
	implementation 'io.micrometer:micrometer-registry-prometheus'

	// For OpenTelemetry
	implementation 'io.opentelemetry:opentelemetry-api:1.41.0'

	testImplementation('org.springframework.boot:spring-boot-starter-test') {
		// Fixes warning about multiple occurrences of JSONObject on the classpath
		exclude group: 'com.vaadin.external.google', module: 'android-json'
	}

	// BouncyCastle for test key generation utilities
	testImplementation 'org.bouncycastle:bcprov-jdk18on:1.82'
	testImplementation 'org.bouncycastle:bcpkix-jdk18on:1.82'

	testImplementation('au.com.dius.pact.provider:junit5:4.6.18')
	testImplementation('au.com.dius.pact.provider:junit5spring:4.6.18')
}

sonar {
	properties {
		property "sonar.projectName", "terra-drs-hub"
		property "sonar.projectKey", "DataBiosphere_terra-drs-hub"
		property "sonar.organization", "broad-databiosphere"
		property "sonar.host.url", "https://sonarcloud.io"
		property "sonar.sources", "src/main/java,src/main/resources/templates"
	}
}

