plugins {
	id 'idea'
	id 'java-library'
	id 'maven-publish'

	id 'com.google.cloud.artifactregistry.gradle-plugin' version '2.2.5'
	id 'org.hidetake.swagger.generator'
}

repositories { mavenCentral() }

apply from: 'publishing.gradle'
apply from: 'swagger.gradle'

// In the future when pursuing a Java upgrade, source and target compatibility may differ:
// sourceCompatibility = JavaLanguageVersion.of(<currentJavaVersion>)
