# This workflow runs DrsHub's nightly tests, which currently only includes (very basic) performance tests

name: Nightly Perf Tests

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [nightly-tests]

jobs:
  performance-tests:
    runs-on: ubuntu-latest

    env:
      PORT: 5432

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Verify perf version matches dev
        run: |
          devVersion=$(curl https://drshub.dsde-dev.broadinstitute.org/version)
          perfVersion=$(curl https://drshub.dsde-perf.broadinstitute.org/version)
          if [ $devVersion != $perfVersion ]; then
            echo "dev version: $devVersion"
            echo "perf version: $perfVersion"
            echo 'Perf and dev versions do not match, are you testing what you think you are testing?'
            exit 1
          fi

      - name: Get version files from terra-helmfile
        env:
          BROADBOT_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
        run: |
          curl -H "Authorization: token ${BROADBOT_TOKEN}" \
            -H 'Accept: application/vnd.github.v3.raw' \
            -L https://api.github.com/repos/broadinstitute/terra-helmfile/contents/versions/app/dev.yaml \
            --create-dirs -o "integration/terra-helmfile/versions/app/dev.yaml"
          curl -H "Authorization: token ${BROADBOT_TOKEN}" \
            -H 'Accept: application/vnd.github.v3.raw' \
            -L https://api.github.com/repos/broadinstitute/terra-helmfile/contents/environments/live/perf.yaml \
            --create-dirs -o "integration/terra-helmfile/environments/live/perf.yaml"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ github.ref }}-${{ github.sha }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ github.ref }}

      # Github workflows shouldn't have access to vault, so we read from GitHub secrets instead.
      - name: Render GitHub Secrets
        env:
          DEV_FIRECLOUD_ACCOUNT_B64: ${{ secrets.DEV_FIRECLOUD_ACCOUNT_B64 }}
          PERF_TESTRUNNER_ACCOUNT_B64: ${{ secrets.PERF_TESTRUNNER_ACCOUNT_B64 }}
        run: |
          echo "$DEV_FIRECLOUD_ACCOUNT_B64" | base64 -d >"./integration/src/main/resources/rendered/user-delegated-sa.json"
          echo "$PERF_TESTRUNNER_ACCOUNT_B64" | base64 -d >"./integration/src/main/resources/rendered/testrunner-sa.json"

      - name: Run the perf test suite
        run: ./gradlew --build-cache runTest --args="suites/FullPerf.json /tmp/test-results"

      - name: Upload results to Google Bucket
        run: ./gradlew uploadResults --args="CompressDirectoryToTerraKernelK8S.json /tmp/test-results"

  notify-slack:
   needs: [ performance-tests ]
   runs-on: ubuntu-latest

   if: failure()

   steps:
    - name: Notify slack on failure
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "workflow_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "workflow_name": "Nightly Perf Tests",
            "branch" : "${{ github.ref }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.TEST_JADE_ALERTS_SLACK_WEBHOOK }}
